### ISSUE TITLE
CMC Chunk Meta Listener Chunk Load Event causes lag spikes

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/CivModCore#84] opened 2021-04-17 23:07 UTC
In this timings at the 11:21-11:25 mark you can see CMC take a massive spike https://timings.aikar.co/?id=60404db8730642f4b38424757b20a309

**Comment by Maxopoly** [comment] 2021-09-05 11:00
Duplicate of https://github.com/CivClassic/CivModCore/issues/84

**Closed as completed by Maxopoly** 2021-09-05 11:00 UTC
Labels: bug

**Comment by Maxopoly** [comment] 2021-09-05 11:11
https://github.com/CivClassic/CivModCore/issues/74 I mean
