### ISSUE TITLE
Chunk Meta thread dump

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/CivModCore#99] opened 2021-05-27 17:01 UTC
https://pastebin.com/m6FndRmN

https://timings.aikar.co/?id=16c6c06bf83b4bb69384c39b2a408b0e

Server locked up, something to do with a player's death causing a chunk meta lag spike in JukeAlert and Citadel

**Comment by wingzero54** [comment] 2021-09-03 02:10
This really big one: https://pastebin.com/r23zV1nY

This locked the server up at least five times today: for 40 seconds, then 5 seconds, then 5 seconds, then 20 seconds, then 5 seconds, then 7 seconds. 

An example of a different smaller one: https://pastebin.com/C9frYPHB

**Comment by wingzero54** [comment] 2021-09-03 03:31
Here's another example of a different sort of CMC thread dump https://pastebin.com/ErriWSas

**Comment by Maxopoly** [comment] 2021-09-05 11:01
Duplicate of https://github.com/CivClassic/CivModCore/issues/84

**Closed as completed by Maxopoly** 2021-09-05 11:01 UTC
